---
# tasks file for mailserver
- name: Create volumes for mail data
  docker_volume:
    name: "{{item}}"
  with_items:
    - "{{mailserver_docker_container}}_maildata"
    - "{{mailserver_docker_container}}_mailstate"
    - "{{mailserver_docker_container}}_config"

- name: "Run mail server '{{mailserver_docker_container}}'"
  register: mail
  docker_container:
    env: "{{mailserver_docker_env}}"
    hostname: "{{mailserver_hostname}}"
    image: "{{mailserver_docker_image}}"
    name: "{{mailserver_docker_container}}"
    ports: "{{mailserver_docker_ports}}"
    pull: yes
    state: started
    volumes: "{{mailserver_docker_volumes}} + [
      '{{mailserver_docker_container}}_maildata:/var/mail',
      '{{mailserver_docker_container}}_mailstate:/var/mail-state',
      '{{mailserver_docker_container}}_config:/tmp/docker-mailserver'
    ]"

- name: "Setup mail server '{{mailserver_docker_container}}'"
  command: |
    docker exec {{mailserver_docker_container}} /bin/sh -c '
      addmailuser {{item.user}} {{item.password}} 2>/dev/null || true
    '
  with_items: "{{mailserver_users}}"
  when:
    - mail.changed

- name: "Generate dkim config for '{{mailserver_docker_container}}'"
  command: "docker exec {{mailserver_docker_container}} generate-dkim-config"
  when:
    - mail.changed